
image: python:3

services:

variables:

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - pip install -r requirements.txt

test:
  script:
  - python3 Portal/manage.py makemigrations
  - python3 Portal/manage.py migrate
  - python3 Portal/manage.py test
