# Generated by Django 2.2.1 on 2019-08-23 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID:')),
                ('Suite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite')),
                ('StreetAddress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Street Address')),
                ('Postal', models.CharField(blank=True, max_length=7, null=True, verbose_name='Postal Code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'addresses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('order', models.CharField(default=False, max_length=50, verbose_name='Order Number')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='Company Name')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('currentProvider', models.CharField(max_length=50, null=True, verbose_name='Current Provider')),
                ('directory_listing', models.BooleanField(null=True, verbose_name='Directory Listing')),
                ('listing_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Listing Name')),
                ('category_listing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Listing')),
                ('listing_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Listing Phone Number')),
                ('listing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_address', to='forms.Address')),
                ('site_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='forms.Address')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='UserCompLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User & Company Relation',
                'verbose_name_plural': 'User & Company Relations',
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'User Uploads',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, verbose_name='Number')),
                ('Type', models.BooleanField(null=True, verbose_name='To Be Ported')),
                ('Address_911', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ext', models.IntegerField(verbose_name='Extension')),
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('caller_id_name', models.CharField(max_length=50, null=True, verbose_name='Caller ID')),
                ('caller_id_number', models.CharField(max_length=16, null=True, verbose_name='Caller ID Number')),
                ('voicemail', models.BooleanField(null=True, verbose_name='Voicemail')),
                ('voicemail_toEmail', models.BooleanField(null=True, verbose_name='Voicemail To Email')),
                ('voicemail_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
            options={
                'verbose_name': 'Extention',
                'verbose_name_plural': 'Extentions',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddressLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Address')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
        ),
    ]
