# Generated by Django 2.2.1 on 2019-06-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Street', models.CharField(max_length=50, verbose_name='Street')),
                ('City', models.CharField(max_length=50, verbose_name='City')),
                ('Province', models.CharField(choices=[('Ontario', 'ON'), ('Quebec', 'QC'), ('British Columbia', 'BC'), ('Alberta', 'AB'), ('Manitoba', 'MB'), ('Saskatchewan', 'SK'), ('Nova Scotia', 'NS'), ('New Brunswick', 'NB'), ('Newfoundland and Labrador', 'NL'), ('Prince Edward Island', 'PE'), ('Northwest Territories', 'NT'), ('Yukon', 'YT'), ('Nunavut', 'NU')], default='Ontario', max_length=2)),
                ('PostalCode', models.CharField(max_length=7, verbose_name='Postal Code - A#A#A#')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('main_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Phone')),
                ('main_fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Fax')),
                ('directory_listing', models.CharField(max_length=50, null=True, verbose_name='Directory Listing')),
                ('listing_name', models.CharField(max_length=50, null=True, verbose_name='Listing Name')),
                ('category_listing', models.CharField(max_length=50, null=True, verbose_name='Category Listing')),
                ('listing_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Listing Phone Number')),
                ('listing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_address', to='forms.Address')),
                ('site_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='forms.Address')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(verbose_name='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='')),
                ('Address_911', models.ManyToManyField(to='forms.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ext', models.IntegerField(verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('caller_id_name', models.CharField(max_length=50, verbose_name='')),
                ('called_id_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='')),
                ('voicemail', models.BooleanField(verbose_name='')),
                ('voicemail_toEmail', models.BooleanField(null=True, verbose_name='')),
                ('voicemail_email', models.EmailField(max_length=254, null=True, verbose_name='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
        ),
    ]
