# Generated by Django 2.2.1 on 2019-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Address',
        ),
        migrations.AddField(
            model_name='address',
            name='StreetAddress',
            field=models.CharField(blank=True, max_length=250, verbose_name='Street Address'),
        ),
    ]
