# Generated by Django 2.2.1 on 2019-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplink',
            name='completed',
        ),
        migrations.AddField(
            model_name='company',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
