# Generated by Django 2.2.1 on 2019-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='order',
            field=models.CharField(max_length=50, null=True, verbose_name='Order'),
        ),
    ]
