# Generated by Django 2.2.1 on 2019-08-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
