# Generated by Django 2.2.1 on 2019-08-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190820_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='MainModel',
        ),
    ]
