# Generated by Django 2.2.1 on 2019-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190603_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Company Name'),
        ),
    ]
