# Generated by Django 2.2.1 on 2019-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20190820_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name': 'Upload', 'verbose_name_plural': 'User Uploads'},
        ),
        migrations.AddField(
            model_name='numbers',
            name='Type1800',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
    ]
