# Generated by Django 2.2.1 on 2019-06-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20190606_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='completed',
            field=models.BooleanField(default=False, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='listing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_address', to='forms.Address'),
        ),
    ]
