# Generated by Django 2.2.1 on 2019-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190820_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbers',
            name='Type1800',
        ),
        migrations.AddField(
            model_name='uploads',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
    ]
