# Generated by Django 2.2.1 on 2019-06-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190606_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='site_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='forms.Address'),
        ),
    ]
