# Generated by Django 2.2.1 on 2019-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20190606_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='PostalCode',
            new_name='Postal',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Province',
        ),
        migrations.AddField(
            model_name='address',
            name='Country',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='address',
            name='Prov',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='address',
            name='StreetNum',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='address',
            name='Suite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(default='', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street',
            field=models.CharField(default='', max_length=50, verbose_name='Street'),
        ),
    ]
