# Generated by Django 2.2.1 on 2019-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20190606_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currentProvider',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
    ]
