# Generated by Django 2.2.1 on 2019-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_company_currentprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(default='', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='StreetNum',
            field=models.IntegerField(default=0, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Suite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='completed',
            field=models.BooleanField(default=False, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currentProvider',
            field=models.CharField(max_length=50, null=True, verbose_name='Current Provider'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type'),
        ),
    ]
