# Generated by Django 2.2.1 on 2019-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20190607_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='main_fax',
        ),
        migrations.RemoveField(
            model_name='company',
            name='main_phone',
        ),
        migrations.AlterField(
            model_name='address',
            name='Prov',
            field=models.CharField(default='', max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='company',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
