# Generated by Django 2.2.1 on 2019-06-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20190607_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',), 'verbose_name': 'Address', 'verbose_name_plural': 'addresses'},
        ),
    ]
