# Generated by Django 2.2.1 on 2019-06-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20190607_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='site_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='forms.Address'),
        ),
        migrations.CreateModel(
            name='CompanyAddressLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Address')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
        ),
    ]
