# Generated by Django 2.2.1 on 2019-06-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20190607_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='extention',
            options={'verbose_name': 'Extention', 'verbose_name_plural': 'Extentions'},
        ),
        migrations.AlterModelOptions(
            name='numbers',
            options={'verbose_name': 'Number', 'verbose_name_plural': 'Numbers'},
        ),
        migrations.AlterModelOptions(
            name='usercomplink',
            options={'verbose_name': 'User & Company Relation', 'verbose_name_plural': 'User & Company Relations'},
        ),
    ]
