# Generated by Django 2.2.1 on 2019-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20190610_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='Type',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
    ]
