# Generated by Django 2.2.1 on 2019-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_numbers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='listing_phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Listing Phone Number'),
        ),
        migrations.AlterField(
            model_name='extention',
            name='called_id_number',
            field=models.CharField(max_length=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.CharField(max_length=12, verbose_name=''),
        ),
    ]
