# Generated by Django 2.2.1 on 2019-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.CharField(help_text='Please use correct Order Number', max_length=40, unique=True, verbose_name='Order ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Used to reach user regarding Password Changes/Resets or Form Issues', max_length=255, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Makes the user an Admin - can access Admin Page and make changes', verbose_name='Superuser')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserPRToken',
            fields=[
                ('userId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=40)),
            ],
        ),
    ]
