# Generated by Django 2.2.1 on 2019-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190529_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='orderId',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Users Login Email', max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
