# Generated by Django 2.2.1 on 2019-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190522_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='orderId',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
