# Generated by Django 2.2.1 on 2019-05-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190522_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='orderId',
        ),
    ]
