# Generated by Django 2.2.1 on 2019-05-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190522_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Used to reach user regarding Password Changes/Resets or Form Issues', max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='orderId',
            field=models.CharField(help_text='Please use correct Order Number', max_length=40, unique=True, verbose_name='Order ID'),
        ),
    ]
