# Generated by Django 2.2.1 on 2019-08-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='report/')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Company')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
